"use client";

import { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Rocket, Pause } from "lucide-react";
import { usePathname, useRouter } from "next/navigation";

// Define the route of the tour
const tourRoutes = ["/", "/services", "/showcase", "/blog", "/about", "/faq", "/contact"];

const AutoPilot = () => {
  const [isAutoPiloting, setIsAutoPiloting] = useState(false);
  const requestRef = useRef();
  const router = useRouter();
  const pathname = usePathname();
  
  const scrollSpeed = 4; // Increased scroll speed for faster touring

  const scrollPage = () => {
    if (!isAutoPiloting) return;
    
    window.scrollBy(0, scrollSpeed);
    
    const scrollPosition = Math.ceil(window.innerHeight + window.scrollY);
    const documentHeight = document.documentElement.scrollHeight;
    
    // If we reached the bottom of the current page
    if (scrollPosition >= documentHeight - 5) {
      goToNextPage();
      return; // Stop scrolling on this page
    }
    
    requestRef.current = requestAnimationFrame(scrollPage);
  };

  const goToNextPage = () => {
    cancelAnimationFrame(requestRef.current);
    
    // Find the current page in the tour
    const currentIndex = tourRoutes.indexOf(pathname);
    let nextIndex = 0;
    
    // If found and not the last page, go to next. Else loop to start.
    if (currentIndex !== -1 && currentIndex < tourRoutes.length - 1) {
      nextIndex = currentIndex + 1;
    } else {
      nextIndex = 0;
    }
    
    const nextRoute = tourRoutes[nextIndex];
    router.push(nextRoute);
  };

  // Effect to handle scrolling when pathname changes (page transition)
  useEffect(() => {
    if (isAutoPiloting) {
      cancelAnimationFrame(requestRef.current);
      // Wait 1.5 seconds at the top of the new page before scrolling again
      const timeout = setTimeout(() => {
        requestRef.current = requestAnimationFrame(scrollPage);
      }, 1500);
      return () => clearTimeout(timeout);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pathname, isAutoPiloting]);

  // Effect to handle manual user interrupt
  useEffect(() => {
    const handleUserInteraction = (e) => {
      // Only stop if the event was generated by a real user interaction
      if (isAutoPiloting && e.isTrusted) {
        setIsAutoPiloting(false);
        cancelAnimationFrame(requestRef.current);
      }
    };
    
    window.addEventListener("wheel", handleUserInteraction, { passive: true });
    window.addEventListener("touchstart", handleUserInteraction, { passive: true });
    window.addEventListener("mousedown", handleUserInteraction, { passive: true });
    
    return () => {
      window.removeEventListener("wheel", handleUserInteraction);
      window.removeEventListener("touchstart", handleUserInteraction);
      window.removeEventListener("mousedown", handleUserInteraction);
    };
  }, [isAutoPiloting]);

  return (
    <AnimatePresence>
      <motion.button
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.8 }}
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        onClick={(e) => {
          e.preventDefault();
          e.stopPropagation(); // prevent triggering the mousedown interrupt
          setIsAutoPiloting(!isAutoPiloting);
        }}
        className={`fixed bottom-6 right-6 z-[60] flex items-center justify-center gap-2 px-5 py-3 rounded-full shadow-[0_0_20px_rgba(0,0,0,0.15)] border overflow-hidden group transition-colors duration-300 ${
          isAutoPiloting 
            ? "bg-orange-500/90 hover:bg-orange-600/90 border-orange-400 dark:border-orange-500 text-white shadow-orange-500/30" 
            : "bg-white/80 dark:bg-gray-800/80 backdrop-blur-md border-gray-200 dark:border-gray-700 text-gray-800 dark:text-gray-100 hover:bg-gray-50 dark:hover:bg-gray-700/80"
        }`}
      >
        {isAutoPiloting ? (
          <>
            <Pause size={20} className="text-white" />
            <span className="font-semibold text-sm tracking-wide">Stop Tour</span>
          </>
        ) : (
          <>
            <Rocket size={20} className="text-orange-500 dark:text-orange-400" />
            <span className="font-semibold text-sm tracking-wide">Site Tour</span>
          </>
        )}
        
        {isAutoPiloting && (
          <span className="absolute -inset-1 rounded-full border-2 border-white/50 animate-ping pointer-events-none" />
        )}
      </motion.button>
    </AnimatePresence>
  );
};

export default AutoPilot;
