export const countryCodes = [
    { code: "+1", country: "US", flag: "🇺🇸" },
    { code: "+44", country: "UK", flag: "🇬🇧" },
    { code: "+91", country: "IN", flag: "🇮🇳" },
    { code: "+880", country: "BD", flag: "🇧🇩" },
    { code: "+61", country: "Australia", flag: "🇦🇺" },
    { code: "+49", country: "Germany", flag: "🇩🇪" },
    { code: "+33", country: "France", flag: "🇫🇷" },
    { code: "+81", country: "Japan", flag: "🇯🇵" },
    { code: "+55", country: "Brazil", flag: "🇧🇷" },
    { code: "+1", country: "Canada", flag: "🇨🇦" },
    { code: "+27", country: "South Africa", flag: "🇿🇦" },
    { code: "+34", country: "Spain", flag: "🇪🇸" },
    { code: "+39", country: "Italy", flag: "🇮🇹" },
    { code: "+52", country: "Mexico", flag: "🇲🇽" },
    { code: "+63", country: "Philippines", flag: "🇵🇭" },
    { code: "+20", country: "Egypt", flag: "🇪🇬" },
    { code: "+7", country: "Russia", flag: "🇷🇺" },
    { code: "+47", country: "Norway", flag: "🇳🇴" },
    { code: "+32", country: "Belgium", flag: "🇧🇪" },
    { code: "+41", country: "Switzerland", flag: "🇨🇭" },
    { code: "+90", country: "Turkey", flag: "🇹🇷" },
    { code: "+966", country: "Saudi Arabia", flag: "🇸🇦" },
    { code: "+82", country: "South Korea", flag: "🇰🇷" },
    { code: "+86", country: "China", flag: "🇨🇳" },
    { code: "+971", country: "UAE", flag: "🇦🇪" },
    { code: "+46", country: "Sweden", flag: "🇸🇪" },
    { code: "+48", country: "Poland", flag: "🇵🇱" },
    { code: "+98", country: "Iran", flag: "🇮🇷" },
    { code: "+45", country: "Denmark", flag: "🇩🇰" },
    { code: "+60", country: "Malaysia", flag: "🇲🇾" },
    { code: "+1", country: "Barbados", flag: "🇧🇧" },
    { code: "+420", country: "Czech Republic", flag: "🇨🇿" },
    { code: "+54", country: "Argentina", flag: "🇦🇷" },
    { code: "+64", country: "New Zealand", flag: "🇳🇿" },
    { code: "+673", country: "Brunei", flag: "🇧🇳" },
    { code: "+62", country: "Indonesia", flag: "🇮🇩" },
    { code: "+380", country: "Ukraine", flag: "🇺🇦" },
    { code: "+354", country: "Iceland", flag: "🇮🇸" },
    { code: "+251", country: "Ethiopia", flag: "🇪🇹" },
    { code: "+353", country: "Ireland", flag: "🇮🇪" },
    { code: "+593", country: "Ecuador", flag: "🇪🇨" },
    { code: "+976", country: "Mongolia", flag: "🇲🇳" },
    { code: "+234", country: "Nigeria", flag: "🇳🇬" },
    { code: "+974", country: "Qatar", flag: "🇶🇦" },
    { code: "+211", country: "South Sudan", flag: "🇸🇸" },
    { code: "+218", country: "Libya", flag: "🇱🇾" },
    { code: "+41", country: "Switzerland", flag: "🇨🇭" },
    { code: "+377", country: "Monaco", flag: "🇲🇨" },
    { code: "+226", country: "Burkina Faso", flag: "🇧🇫" },
    { code: "+963", country: "Syria", flag: "🇸🇾" },
    { code: "+506", country: "Costa Rica", flag: "🇨🇷" },
    { code: "+598", country: "Uruguay", flag: "🇺🇾" },
    { code: "+503", country: "El Salvador", flag: "🇸🇻" },
    { code: "+56", country: "Chile", flag: "🇨🇱" },
    { code: "+264", country: "Namibia", flag: "🇳🇦" },
    { code: "+92", country: "Pakistan", flag: "🇵🇰" },
    { code: "+975", country: "Bhutan", flag: "🇧🇹" },
    { code: "+228", country: "Togo", flag: "🇹🇬" },
    { code: "+267", country: "Botswana", flag: "🇧🇼" },
    { code: "+389", country: "North Macedonia", flag: "🇲🇰" },
    { code: "+355", country: "Albania", flag: "🇦🇱" },
    { code: "+963", country: "Syria", flag: "🇸🇾" },
    { code: "+222", country: "Mauritania", flag: "🇲🇷" },
    { code: "+240", country: "Gabon", flag: "🇬🇦" },
    { code: "+233", country: "Ghana", flag: "🇬🇭" },
    { code: "+226", country: "Burkina Faso", flag: "🇧🇫" },
    { code: "+355", country: "Albania", flag: "🇦🇱" },
    { code: "+260", country: "Zambia", flag: "🇿🇲" },
    { code: "+503", country: "El Salvador", flag: "🇸🇻" },
    { code: "+599", country: "Curaçao", flag: "🇨🇼" },
    { code: "+228", country: "Togo", flag: "🇹🇬" },
    { code: "+34", country: "Spain", flag: "🇪🇸" },
    { code: "+251", country: "Ethiopia", flag: "🇪🇹" },
    { code: "+680", country: "Palau", flag: "🇵🇼" },
    { code: "+691", country: "Federated States of Micronesia", flag: "🇫🇲" },
    { code: "+680", country: "Palau", flag: "🇵🇼" },
    { code: "+960", country: "Maldives", flag: "🇲🇻" },
    { code: "+259", country: "Mozambique", flag: "🇲🇿" },
    { code: "+256", country: "Uganda", flag: "🇺🇬" },
    { code: "+260", country: "Zambia", flag: "🇿🇲" }
];
