// app/layout.js (or app/rootLayout.js if you're using the app directory)
import { Geist, Geist_Mono } from "next/font/google";
import CustomCursor from "./compo/CustomCursor";
import Navbar from "./compo/Navbar"; // Ensure the path is correct
import AutoPilot from "./compo/AutoPilot"; // Add the AutoPilot component
import "./globals.css";

// Load the fonts from Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define metadata for the document
export const metadata = {
  title: "xwebhub",
  description: "Generated by create next app",
  manifest: "/manifest.json", // Path to the manifest file
  icons: {
    icon: "/icons/icon-192x192.png", // Path to favicon (inside `public/` folder)
  },
};

// Root layout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}  // Apply fonts to the body
      >
        <svg className="fixed inset-0 w-full h-full pointer-events-none z-0 opacity-40 dark:opacity-20 mix-blend-overlay">
          <filter id="noiseFilter">
            <feTurbulence type="fractalNoise" baseFrequency="0.65" numOctaves="3" stitchTiles="stitch"/>
          </filter>
          <rect width="100%" height="100%" filter="url(#noiseFilter)"/>
        </svg>
        <CustomCursor />
        <AutoPilot /> {/* Floating auto pilot button */}
        <Navbar />  {/* Navbar component */}
        {children}  {/* Render the content passed to the layout */}
      </body>
    </html>
  );
}
