// app/layout.js (or app/rootLayout.js if you're using the app directory)
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./compo/Navbar";  // Ensure the path is correct

// Load the fonts from Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define metadata for the document
export const metadata = {
  title: "xwebhub",
  description: "Generated by create next app",
  manifest: "/manifest.json", // Path to the manifest file
  icons: {
    icon: "/icons/icon-192x192.png", // Path to favicon (inside `public/` folder)
  },
};

// Root layout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}  // Apply fonts to the body
      >
        <Navbar />  {/* Navbar component */}
        {children}  {/* Render the content passed to the layout */}
      </body>
    </html>
  );
}
